### Project Phase 01 — Dataset Familiarization
#### Difficulty: Beginner

In [3]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\prasa\appdata\local\programs\python\python314\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\prasa\appdata\local\programs\python\python314\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
data=pd.read_excel("Online_Retail_Practice.xlsx")
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [5]:
data.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden

In [6]:
data.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1602,576798,22633,HAND WARMER UNION JACK,8,2011-03-20 15:46:00,2.10,16068.0,Australia
1603,549401,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,2011-05-25 22:09:00,3.40,13436.0,Portugal
1604,565607,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,1,2011-07-24 17:52:00,2.71,13346.0,Netherlands
1605,569476,22423,REGENCY CAKESTAND 3 TIER,4,2011-04-19 21:53:00,12.75,17314.0,Sweden
1606,C554322,21212,PACK OF 72 RETROSPOT CAKE CASES,-6,2011-08-16 02:22:00,0.55,18187.0,Sweden
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [7]:
data.sample(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
513,565922,79323P,PINK CHERRY LIGHTS,13,2010-12-09 13:16:00,6.75,17371.0,EIRE
238,556824,71053,WHITE METAL LANTERN,6,2011-11-05 21:47:00,2.71,17022.0,United Kingdom
1342,546907,85123A,WHITE HANGING HEART T-LIGHT HOLDER,4,2011-06-18 11:43:00,2.55,12705.0,France
497,561669,21730,GLASS STAR FROSTED T-LIGHT HOLDER,8,2011-02-01 01:20:00,4.25,14894.0,Spain
688,544800,79323P,PINK CHERRY LIGHTS,5,2011-09-09 05:20:00,6.75,14947.0,EIRE
611,540924,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-28 19:47:00,12.75,17137.0,Belgium
1419,566736,71053,WHITE METAL LANTERN,6,2011-05-30 05:10:00,4.07,15258.0,Belgium
101,573603,POST,POSTAGE,8,2011-03-16 11:27:00,21.60,14863.0,Australia
580,537415,22423,REGENCY CAKESTAND 3 TIER,7,2011-02-27 20:19:00,15.30,13643.0,Belgium
827,568306,22633,HAND WARMER UNION JACK,6,2011-04-04 14:26:00,2.10,16540.0,United Kingdom
1493,556798,79323P,PINK CHERRY LIGHTS,5,2011-04-06 21:24:00,5.40,17949.0,Netherlands
640,551245,22752,SET 7 BABUSHKA NESTING BOXES,7,2011-03-16 03:55:00,9.18,17433.0,Australia
1586,549783,21730,GLASS STAR FROSTED T-LIGHT HOLDER,3,2011-04-03 10:47:00,4.25,17106.0,Sweden
851,548074,79323P,PINK CHERRY LIGHTS,9,2011-01-28 05:11:00,6.75,17842.0,Australia
1115,556396,84406B,CREAM CUPID HEARTS COAT HANGER,1,2011-02-19 22:05:00,2.75,17726.0,EIRE

In [8]:
data.shape

(1612, 8)

In [9]:
data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [10]:
data.dtypes

InvoiceNo                 str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

In [13]:
data=data.drop_duplicates()
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1595,564607,POST,POSTAGE,15,2011-07-02 04:57:00,18.00,13500.0,Netherlands
1596,576989,85123A,WHITE HANGING HEART T-LIGHT HOLDER,10,2011-08-14 10:06:00,3.06,13704.0,Australia
1597,C555041,79323P,PINK CHERRY LIGHTS,-14,2011-11-06 12:02:00,6.75,14111.0,France
1598,567397,71053,WHITE METAL LANTERN,8,2011-03-13 19:34:00,3.39,17260.0,United Kingdom
1599,570077,21730,GLASS STAR FROSTED T-LIGHT HOLDER,10,2011-09-23 17:30:00,4.25,12345.0,Belgium

In [14]:
data["Description"].head(20)

0                     WHITE METAL LANTERN
1       GLASS STAR FROSTED T-LIGHT HOLDER
2     KNITTED UNION FLAG HOT WATER BOTTLE
3                     WHITE METAL LANTERN
4     KNITTED UNION FLAG HOT WATER BOTTLE
5     KNITTED UNION FLAG HOT WATER BOTTLE
6                                 POSTAGE
7                                 POSTAGE
8      PACK OF 60 PINK PAISLEY CAKE CASES
9                     WHITE METAL LANTERN
10                 HAND WARMER UNION JACK
11        PACK OF 72 RETROSPOT CAKE CASES
12                                POSTAGE
13           SET 7 BABUSHKA NESTING BOXES
14      GLASS STAR FROSTED T-LIGHT HOLDER
15     PACK OF 60 PINK PAISLEY CAKE CASES
16                                POSTAGE
17               REGENCY CAKESTAND 3 TIER
18                     PINK CHERRY LIGHTS
19               REGENCY CAKESTAND 3 TIER
Name: Description, dtype: str

In [15]:
data.describe()

          Quantity                 InvoiceDate    UnitPrice    CustomerID
count  1600.000000                        1600  1600.000000   1529.000000
mean      7.173750  2011-06-06 10:58:42.637500     5.518756  15197.037933
min     -15.000000         2010-12-01 00:05:00     0.000000  12305.000000
25%       4.000000         2011-03-05 14:10:45     2.200000  13717.000000
50%       8.000000         2011-06-07 08:34:00     3.390000  15200.000000
75%      12.000000         2011-09-08 05:02:45     7.650000  16636.000000
max      15.000000         2011-12-08 18:19:00    21.600000  18196.000000
std       5.880597                         NaN     5.184696   1692.191251

### Project Phase 02 — DataFrame Exploration
#### Difficulty: Beginner

In [58]:
o=pd.read_excel("Online_Retail_Practice.xlsx")
d=pd.DataFrame(o[["InvoiceNo", "StockCode", "Description", "Quantity", "UnitPrice", "CustomerID", "Country"]])
d

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17296.0,Germany

In [59]:
df=pd.DataFrame(d.head(10))
df

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,3.39,16830.0,Sweden
5,561166,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,3,4.07,12343.0,Spain
6,570510,POST,POSTAGE,4,14.40,12767.0,United Kingdom
7,574557,POST,POSTAGE,1,21.60,13566.0,France
8,572698,21977,PACK OF 60 PINK PAISLEY CAKE CASES,2,0.55,14765.0,Germany
9,547022,71053,WHITE METAL LANTERN,7,4.07,15256.0,EIRE

In [60]:
d[["Quantity","UnitPrice" ]].describe()

          Quantity    UnitPrice
count  1612.000000  1612.000000
mean      7.158189     5.523189
std       5.890089     5.191564
min     -15.000000     0.000000
25%       4.000000     2.200000
50%       8.000000     3.390000
75%      12.000000     7.650000
max      15.000000    21.600000

In [29]:
d[["Country","Description" ]].describe()

       Country Description
count     1599        1589
unique      10          22
top     France     POSTAGE
freq       178         143

In [61]:
d.info()

<class 'pandas.DataFrame'>
RangeIndex: 1612 entries, 0 to 1611
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    1612 non-null   str
 1   StockCode    1612 non-null   str
 2   Description  1589 non-null   str
 3   Quantity     1612 non-null   int64
 4   UnitPrice    1612 non-null   float64
 5   CustomerID   1541 non-null   float64
 6   Country      1599 non-null   str
dtypes: float64(2), int64(1), str(4)
memory usage: 158.7 KB

In [39]:
a=d[d.notnull()]
a

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17296.0,Germany

In [40]:
d.nunique()

InvoiceNo      1574
StockCode        12
Description      22
Quantity         31
UnitPrice        31
CustomerID     1346
Country          10
dtype: int64

In [62]:
print(d["Country"].unique())
b=d["Country"].nunique()
print(b)

<ArrowStringArray>
[        'Sweden',    'Netherlands',          'Spain', 'United Kingdom',
         'France',        'Germany',           'EIRE',       'Portugal',
        'Belgium',      'Australia',              nan]
Length: 11, dtype: str
10

In [48]:
top = d['Country'].value_counts()
print(top)

Country
France            178
Spain             165
Australia         165
Belgium           164
Sweden            162
United Kingdom    160
Netherlands       158
EIRE              155
Portugal          147
Germany           145
Name: count, dtype: int64

In [63]:
df={
    "row":[d.shape[0]],
    "col":[d.shape[1]],
    "Unique_prod":[d["Description"].nunique()],
    "Unique_invoices":[d["InvoiceNo"].nunique()]
}
df=pd.DataFrame(df)
df

    row  col  Unique_prod  Unique_invoices
0  1612    7           22             1574

In [64]:
d.to_csv("FinalDataSet.csv",index=False)

### Project Phase 03 — Data Selection and Filtering
#### Difficulty: Beginner to Intermediate

In [70]:
d=o.copy()
d=pd.DataFrame(d)
d

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [71]:
print(d[["InvoiceNo","InvoiceDate"]])

     InvoiceNo         InvoiceDate
0       570338 2011-09-15 15:26:00
1       574674 2011-06-05 08:10:00
2       545052 2011-07-24 03:45:00
3       567005 2011-09-04 16:55:00
4       573512 2011-02-23 13:40:00
...        ...                 ...
1607    546730 2011-09-20 00:21:00
1608    556479 2011-11-13 09:05:00
1609   C541876 2011-04-07 12:48:00
1610    553299 2011-09-24 16:24:00
1611    537515 2011-08-24 00:48:00

[1612 rows x 2 columns]

In [73]:
d.at[1,"Description"]

'GLASS STAR FROSTED T-LIGHT HOLDER'

In [74]:
d.iloc[0:2]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden

In [75]:
d.loc[2:3]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain

In [77]:
d[d["Quantity"]>10]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
10,567596,22633,HAND WARMER UNION JACK,15,2011-07-24 14:21:00,1.68,15220.0,France
18,580659,79323P,PINK CHERRY LIGHTS,15,2011-06-11 21:15:00,8.10,18019.0,Sweden
...,...,...,...,...,...,...,...,...
1593,560762,21730,GLASS STAR FROSTED T-LIGHT HOLDER,11,2011-07-22 02:33:00,4.25,15530.0,Belgium
1595,564607,POST,POSTAGE,15,2011-07-02 04:57:00,18.00,13500.0,Netherlands
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.60,13594.0,United Kingdom
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE

In [80]:
d[d["UnitPrice"]>50]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [83]:
d[d["Country"]=="Spain"]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
5,561166,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,3,2011-02-28 16:38:00,4.07,12343.0,Spain
14,540057,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,2011-04-09 14:35:00,3.40,12683.0,Spain
41,579585,22423,REGENCY CAKESTAND 3 TIER,2,2011-10-24 15:07:00,10.20,16347.0,Spain
54,550375,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-29 06:33:00,2.55,NaN,Spain
...,...,...,...,...,...,...,...,...
1530,548587,21730,GLASS STAR FROSTED T-LIGHT HOLDER,11,2011-10-09 20:02:00,4.25,16434.0,Spain
1544,560857,21977,PACK OF 60 PINK PAISLEY CAKE CASES,5,2011-09-21 00:20:00,0.66,14002.0,Spain
1589,559197,22633,HAND WARMER UNION JACK,14,2010-12-21 15:23:00,2.52,12666.0,Spain
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain

In [88]:
x=d["Country"].value_counts().head(5).index
y=d[d["Country"].isin(x)]
y

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
5,561166,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,3,2011-02-28 16:38:00,4.07,12343.0,Spain
...,...,...,...,...,...,...,...,...
1602,576798,22633,HAND WARMER UNION JACK,8,2011-03-20 15:46:00,2.10,16068.0,Australia
1605,569476,22423,REGENCY CAKESTAND 3 TIER,4,2011-04-19 21:53:00,12.75,17314.0,Sweden
1606,C554322,21212,PACK OF 72 RETROSPOT CAKE CASES,-6,2011-08-16 02:22:00,0.55,18187.0,Sweden
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain

In [90]:
d[d["Quantity"].between(5,20)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
9,547022,71053,WHITE METAL LANTERN,7,2011-09-14 17:41:00,4.07,15256.0,EIRE
...,...,...,...,...,...,...,...,...
1603,549401,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,2011-05-25 22:09:00,3.40,13436.0,Portugal
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [91]:
d[(d["Quantity"]>10) & (d["UnitPrice"]>5)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
18,580659,79323P,PINK CHERRY LIGHTS,15,2011-06-11 21:15:00,8.10,18019.0,Sweden
31,550785,22423,REGENCY CAKESTAND 3 TIER,15,2011-09-25 21:14:00,12.75,16898.0,Netherlands
38,566325,22423,REGENCY CAKESTAND 3 TIER,11,2011-01-14 18:07:00,10.20,13528.0,Sweden
69,566686,22423,REGENCY CAKESTAND 3 TIER,13,2011-06-14 08:46:00,12.75,15782.0,United Kingdom
89,577425,22752,SET 7 BABUSHKA NESTING BOXES,14,2011-11-16 02:46:00,6.12,16327.0,Sweden
...,...,...,...,...,...,...,...,...
1575,547919,22423,REGENCY CAKESTAND 3 TIER,11,2011-04-09 18:38:00,12.75,16277.0,EIRE
1587,572765,21730,GLASS STAR FROSTED T-LIGHT HOLDER,15,2010-12-12 17:20:00,5.10,17421.0,Belgium
1595,564607,POST,POSTAGE,15,2011-07-02 04:57:00,18.00,13500.0,Netherlands
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.60,13594.0,United Kingdom
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE

In [93]:
d.sort_values(by="UnitPrice",ascending=False).head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1248,565100,POST,POSTAGE,14,2011-11-25 20:27:00,21.6,13873.0,Australia
1253,573477,POST,POSTAGE,8,2011-04-22 14:47:00,21.6,18172.0,EIRE
49,557529,POST,POSTAGE,7,2011-08-19 06:38:00,21.6,17690.0,Australia
465,569506,POST,POSTAGE,6,2011-11-08 11:22:00,21.6,16513.0,Australia
932,C561717,POST,POSTAGE,-11,2011-11-22 12:10:00,21.6,15675.0,Netherlands
1528,565108,POST,POSTAGE,10,2011-03-29 08:51:00,21.6,16176.0,France
1560,567925,POST,POSTAGE,4,2011-01-20 13:21:00,21.6,17041.0,France
101,573603,POST,POSTAGE,8,2011-03-16 11:27:00,21.6,14863.0,Australia
764,572968,POST,POSTAGE,6,2011-07-22 19:28:00,21.6,16251.0,Germany
502,C543573,POST,POSTAGE,-15,2011-05-26 09:37:00,21.6,17799.0,Spain
833,574836,POST,POSTAGE,2,2011-05-21 21:25:00,21.6,14562.0,EIRE
501,552616,POST,POSTAGE,6,2011-05-15 13:37:00,21.6,12473.0,France
752,549960,POST,POSTAGE,15,2011-10-20 05:17:00,21.6,14865.0,Australia
353,570905,POST,POSTAGE,12,2011-05-18 16:49:00,21.6,NaN,United Kingdom
359,547600,POST,POSTAGE,8,2011-10-08 10:31:00,21.6,14477.0,Portugal
456,578392,POST,POSTAGE,1,2010-12-16 14:40:00,21.6,15550.0,Germany
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.6,13594.0,United Kingdom
7,574557,POST,POSTAGE,1,2011-09-23 07:36:00,21.6,13566.0,France
617,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.6,13594.0,United Kingdom
893,565522,POST,POSTAGE,1,2011-08-02 16:33:00,21.6,13623.0,United Kingdom

## Project Phase 04 — Data Transformation and Management
### Difficulty: Intermediate

In [4]:
import numpy as np
import pandas as pd
d=pd.read_excel("Online_Retail_Practice.xlsx")
d=pd.DataFrame(d)
df_raw=d.copy()
df=df_raw.copy()
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [7]:
df.rename(columns={"Description":"ProductDescription"},inplace=True)
df

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [9]:
df["Revenue"]=df["Quantity"]*df["UnitPrice"]
df

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden,28.49
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden,59.50
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands,0.00
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain,40.68
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden,50.85
...,...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain,59.50
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE,165.75
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain,-35.70
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal,20.40
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany,15.30

In [11]:
df["TransactionType"] = np.select(
    [
        df["InvoiceNo"].astype("string").str.startswith("C", na=False),
        df["Quantity"] < 0,
        df["Quantity"] > 0,
        (df["Quantity"] == 0) | df["Quantity"].isna()
    ],
    [
        "cancellation",
        "return",
        "positive sale",
        "other/invalid"
    ],
    default="other/invalid"
)
df

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,TransactionType
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden,28.49,positive sale
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden,59.50,positive sale
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands,0.00,other/invalid
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain,40.68,positive sale
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden,50.85,positive sale
...,...,...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain,59.50,positive sale
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE,165.75,positive sale
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain,-35.70,cancellation
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal,20.40,positive sale
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany,15.30,positive sale

In [13]:
df["IsIdentifiedCustomer"] = df["CustomerID"].notnull()
df

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,TransactionType,IsIdentifiedCustomer
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden,28.49,positive sale,True
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden,59.50,positive sale,True
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands,0.00,other/invalid,True
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain,40.68,positive sale,True
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden,50.85,positive sale,True
...,...,...,...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain,59.50,positive sale,True
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE,165.75,positive sale,True
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain,-35.70,cancellation,True
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal,20.40,positive sale,True
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany,15.30,positive sale,True

In [14]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], errors="coerce")
df

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,TransactionType,IsIdentifiedCustomer
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden,28.49,positive sale,True
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden,59.50,positive sale,True
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands,0.00,other/invalid,True
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain,40.68,positive sale,True
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden,50.85,positive sale,True
...,...,...,...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain,59.50,positive sale,True
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE,165.75,positive sale,True
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain,-35.70,cancellation,True
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal,20.40,positive sale,True
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany,15.30,positive sale,True

In [15]:
for col in ["InvoiceNo", "StockCode", "Country"]:
    df[col] = df[col].astype("string")
df

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,TransactionType,IsIdentifiedCustomer
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden,28.49,positive sale,True
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden,59.50,positive sale,True
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands,0.00,other/invalid,True
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain,40.68,positive sale,True
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden,50.85,positive sale,True
...,...,...,...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain,59.50,positive sale,True
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE,165.75,positive sale,True
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain,-35.70,cancellation,True
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal,20.40,positive sale,True
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany,15.30,positive sale,True

In [16]:
first_cols = [
    "InvoiceNo",
    "InvoiceDate",
    "StockCode",
    "ProductDescription",
    "CustomerID",
    "Country",
    "Quantity",
    "UnitPrice",
    "Revenue",
    "TransactionType",
    "IsIdentifiedCustomer"
]
ordered_cols=first_cols+[
    col for col in df.columns if col not in first_cols
]
df=df[ordered_cols]
df

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,Country,Quantity,UnitPrice,Revenue,TransactionType,IsIdentifiedCustomer
0,570338,2011-09-15 15:26:00,71053,WHITE METAL LANTERN,16640.0,Sweden,7,4.07,28.49,positive sale,True
1,574674,2011-06-05 08:10:00,21730,GLASS STAR FROSTED T-LIGHT HOLDER,17154.0,Sweden,14,4.25,59.50,positive sale,True
2,545052,2011-07-24 03:45:00,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,16783.0,Netherlands,0,3.39,0.00,other/invalid,True
3,567005,2011-09-04 16:55:00,71053,WHITE METAL LANTERN,14222.0,Spain,12,3.39,40.68,positive sale,True
4,573512,2011-02-23 13:40:00,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,16830.0,Sweden,15,3.39,50.85,positive sale,True
...,...,...,...,...,...,...,...,...,...,...,...
1607,546730,2011-09-20 00:21:00,21730,GLASS STAR FROSTED T-LIGHT HOLDER,16326.0,Spain,14,4.25,59.50,positive sale,True
1608,556479,2011-11-13 09:05:00,22423,REGENCY CAKESTAND 3 TIER,13615.0,EIRE,13,12.75,165.75,positive sale,True
1609,C541876,2011-04-07 12:48:00,21730,GLASS STAR FROSTED T-LIGHT HOLDER,16943.0,Spain,-7,5.10,-35.70,cancellation,True
1610,553299,2011-09-24 16:24:00,85123A,WHITE HANGING HEART T-LIGHT HOLDER,17478.0,Portugal,8,2.55,20.40,positive sale,True
1611,537515,2011-08-24 00:48:00,85123A,WHITE HANGING HEART T-LIGHT HOLDER,17296.0,Germany,6,2.55,15.30,positive sale,True

In [17]:
df = df.sort_values(
    by=["InvoiceDate", "InvoiceNo"],
    na_position="last"
)
df

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,Country,Quantity,UnitPrice,Revenue,TransactionType,IsIdentifiedCustomer
1523,569444,2010-12-01 00:05:00,71053,WHITE METAL LANTERN,13845.0,Germany,15,3.39,50.85,positive sale,True
122,C543863,2010-12-01 02:26:00,84406B,CREAM CUPID HEARTS COAT HANGER,14319.0,France,-13,2.75,-35.75,cancellation,True
409,568184,2010-12-01 03:57:00,84406B,CREAM CUPID HEARTS COAT HANGER,15058.0,France,3,2.20,6.60,positive sale,True
78,C551232,2010-12-01 06:06:00,71053,WHITE METAL LANTERN,12472.0,Spain,-7,4.07,-28.49,cancellation,True
1312,536850,2010-12-01 21:38:00,22423,REGENCY CAKESTAND 3 TIER,12972.0,Sweden,9,10.20,91.80,positive sale,True
...,...,...,...,...,...,...,...,...,...,...,...
1532,558153,2011-12-08 04:14:00,84406B,CREAM CUPID HEARTS COAT HANGER,12313.0,Sweden,8,2.75,22.00,positive sale,True
831,542017,2011-12-08 06:50:00,85123A,WHITE HANGING HEART T-LIGHT HOLDER,13029.0,France,2,3.06,6.12,positive sale,True
1161,544435,2011-12-08 07:15:00,21730,GLASS STAR FROSTED T-LIGHT HOLDER,15446.0,Netherlands,6,5.10,30.60,positive sale,True
801,572572,2011-12-08 17:37:00,79323P,PINK CHERRY LIGHTS,12426.0,Belgium,5,6.75,33.75,positive sale,True
21,579630,2011-12-08 18:19:00,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,13148.0,Germany,15,3.39,50.85,positive sale,True

In [18]:
df.reset_index(drop=True, inplace=True)
df

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,Country,Quantity,UnitPrice,Revenue,TransactionType,IsIdentifiedCustomer
0,569444,2010-12-01 00:05:00,71053,WHITE METAL LANTERN,13845.0,Germany,15,3.39,50.85,positive sale,True
1,C543863,2010-12-01 02:26:00,84406B,CREAM CUPID HEARTS COAT HANGER,14319.0,France,-13,2.75,-35.75,cancellation,True
2,568184,2010-12-01 03:57:00,84406B,CREAM CUPID HEARTS COAT HANGER,15058.0,France,3,2.20,6.60,positive sale,True
3,C551232,2010-12-01 06:06:00,71053,WHITE METAL LANTERN,12472.0,Spain,-7,4.07,-28.49,cancellation,True
4,536850,2010-12-01 21:38:00,22423,REGENCY CAKESTAND 3 TIER,12972.0,Sweden,9,10.20,91.80,positive sale,True
...,...,...,...,...,...,...,...,...,...,...,...
1607,558153,2011-12-08 04:14:00,84406B,CREAM CUPID HEARTS COAT HANGER,12313.0,Sweden,8,2.75,22.00,positive sale,True
1608,542017,2011-12-08 06:50:00,85123A,WHITE HANGING HEART T-LIGHT HOLDER,13029.0,France,2,3.06,6.12,positive sale,True
1609,544435,2011-12-08 07:15:00,21730,GLASS STAR FROSTED T-LIGHT HOLDER,15446.0,Netherlands,6,5.10,30.60,positive sale,True
1610,572572,2011-12-08 17:37:00,79323P,PINK CHERRY LIGHTS,12426.0,Belgium,5,6.75,33.75,positive sale,True
1611,579630,2011-12-08 18:19:00,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,13148.0,Germany,15,3.39,50.85,positive sale,True

## Project Phase 05 — Data Quality and Missing-Value Management
### Difficulty: Intermediate

In [20]:
d.isnull().sum()
d.isnull().mean() * 100

InvoiceNo      0.000000
StockCode      0.000000
Description    1.426799
Quantity       0.000000
InvoiceDate    0.000000
UnitPrice      0.000000
CustomerID     4.404467
Country        0.806452
dtype: float64

In [21]:
print((d.isnull().mean() * 100).sort_values(ascending=False))

CustomerID     4.404467
Description    1.426799
Country        0.806452
InvoiceNo      0.000000
Quantity       0.000000
StockCode      0.000000
UnitPrice      0.000000
InvoiceDate    0.000000
dtype: float64

In [22]:
print(d[d["CustomerID"].isnull()])
print(d["CustomerID"].isnull().sum())

     InvoiceNo StockCode                         Description  Quantity  \
43      540401     71053                 WHITE METAL LANTERN        10
54      550375    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6
81      562708     71053                 WHITE METAL LANTERN         4
85      553691     22633              HAND WARMER UNION JACK        12
138     540081    79323P                  PINK CHERRY LIGHTS         2
...        ...       ...                                 ...       ...
1476    574763     21730   GLASS STAR FROSTED T-LIGHT HOLDER         4
1478    546251     22752        SET 7 BABUSHKA NESTING BOXES        15
1516    575732     22423            REGENCY CAKESTAND 3 TIER         5
1529   C562164    79323P                  PINK CHERRY LIGHTS        -4
1537    538048     22423            REGENCY CAKESTAND 3 TIER         9

             InvoiceDate  UnitPrice  CustomerID         Country
43   2011-08-06 23:01:00       3.39         NaN          Sweden
54   2010-12-29 06:33:00       2.55         NaN           Spain
81   2011-08-21 14:28:00       3.39         NaN           Spain
85   2011-08-16 01:10:00       0.00         NaN         Germany
138  2011-11-18 20:23:00       0.00         NaN  United Kingdom
...                  ...        ...         ...             ...
1476 2011-08-17 01:13:00       5.10         NaN          Sweden
1478 2011-05-27 01:08:00       7.65         NaN       Australia
1516 2011-04-24 15:00:00      15.30         NaN  United Kingdom
1529 2011-03-23 20:56:00       6.75         NaN           Spain
1537 2011-01-26 01:59:00      12.75         NaN  United Kingdom

[71 rows x 8 columns]
71

In [23]:
print(d[d["Description"].isnull() |
        d["Description"].str.strip().eq("")])

     InvoiceNo StockCode Description  Quantity         InvoiceDate  UnitPrice  \
205     578854     71053         NaN         7 2011-10-04 13:55:00       3.39
267     572385    79323P         NaN         1 2011-06-10 16:31:00       8.10
303     559978    85123A         NaN        14 2010-12-08 10:14:00       2.04
503     554099     22633         NaN         2 2011-03-12 12:39:00       2.10
510     572899    79323P         NaN        11 2011-01-06 07:02:00       5.40
578     537522     22423         NaN        14 2011-08-12 01:07:00      12.75
711     539070     71053         NaN         4 2010-12-06 21:35:00       3.39
737     561823     21977         NaN        12 2011-07-02 06:23:00       0.66
781     537284     21977         NaN         9 2011-02-12 18:56:00       0.44
841    C547433      POST         NaN        -2 2011-07-04 20:48:00      18.00
917    C566354     71053         NaN        -4 2011-05-01 18:46:00       2.71
950     547347     21730         NaN        10 2011-01-10 23:47:00       3.40
1038    574284     22423         NaN         5 2011-05-19 16:30:00      12.75
1052    542751     21730         NaN         7 2011-01-14 08:14:00       4.25
1078    552366      POST         NaN         2 2011-06-01 15:42:00      18.00
1096    556807     71053         NaN        11 2010-12-21 05:17:00       3.39
1195    551929     21977         NaN        15 2011-04-30 01:35:00       0.55
1226    565746    84029G         NaN         3 2011-12-01 23:38:00       3.39
1319    580090     21212         NaN        10 2011-08-24 14:53:00       0.55
1323    569468     22752         NaN        15 2011-10-24 13:30:00       7.65
1394    550113     21977         NaN         6 2011-08-30 04:01:00       0.66
1446    561900     22633         NaN         3 2011-01-28 07:58:00       2.10
1504    564709     22752         NaN         5 2011-09-23 14:12:00       6.12

      CustomerID         Country
205      15358.0          Sweden
267      15755.0     Netherlands
303      14249.0         Germany
503      13832.0  United Kingdom
510      14260.0         Germany
578      16779.0            EIRE
711      14099.0       Australia
737      16012.0  United Kingdom
781      14195.0       Australia
841      16058.0        Portugal
917      17168.0  United Kingdom
950          NaN        Portugal
1038     12445.0     Netherlands
1052         NaN  United Kingdom
1078     12632.0           Spain
1096     15636.0         Belgium
1195     13115.0         Germany
1226     16066.0  United Kingdom
1319     14881.0          France
1323     16229.0         Belgium
1394     15250.0           Spain
1446     14208.0         Belgium
1504     14460.0            EIRE

In [24]:
report = pd.DataFrame({
    "Missing": d.isnull().sum(),
    "NonMissing": d.notnull().sum(),
    "Percentage": d.isnull().mean() * 100
})
print(report)

             Missing  NonMissing  Percentage
InvoiceNo          0        1612    0.000000
StockCode          0        1612    0.000000
Description       23        1589    1.426799
Quantity           0        1612    0.000000
InvoiceDate        0        1612    0.000000
UnitPrice          0        1612    0.000000
CustomerID        71        1541    4.404467
Country           13        1599    0.806452

In [25]:
print(d.duplicated().sum())

12

In [26]:
df = d.drop_duplicates().copy()
print("Before:", len(d))
print("After:", len(df))

Before: 1612
After: 1600

In [27]:
print(df[df.duplicated(
    ["InvoiceNo", "StockCode"], keep=False
)])

     InvoiceNo StockCode          Description  Quantity         InvoiceDate  \
175     574232     71053  WHITE METAL LANTERN         7 2011-01-30 18:38:00
1104    574232     71053  WHITE METAL LANTERN         5 2011-02-24 01:55:00

      UnitPrice  CustomerID      Country
175        3.39     13764.0       Sweden
1104       3.39     17582.0  Netherlands

In [29]:
df["Description"] = df["Description"].replace(
    r"^\s*$", pd.NA, regex=True
).fillna("Unknown Description")
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1595,564607,POST,POSTAGE,15,2011-07-02 04:57:00,18.00,13500.0,Netherlands
1596,576989,85123A,WHITE HANGING HEART T-LIGHT HOLDER,10,2011-08-14 10:06:00,3.06,13704.0,Australia
1597,C555041,79323P,PINK CHERRY LIGHTS,-14,2011-11-06 12:02:00,6.75,14111.0,France
1598,567397,71053,WHITE METAL LANTERN,8,2011-03-13 19:34:00,3.39,17260.0,United Kingdom
1599,570077,21730,GLASS STAR FROSTED T-LIGHT HOLDER,10,2011-09-23 17:30:00,4.25,12345.0,Belgium

In [30]:
print("Before rows:", len(d))
print("After rows:", len(df))
print("Before missing:", d.isnull().sum().sum())
print("After missing:", df.isnull().sum().sum())

Before rows: 1612
After rows: 1600
Before missing: 107
After missing: 84